// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmhhtubytyzbzybgzggm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtaGh0dWJ5dHl6Ynp5Ymd6Z2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzI3MTYsImV4cCI6MjA1ODY0ODcxNn0.NKXZfLCMU7y95lmYBqJANCPZG5aAb94lXttuqbph0-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);